macromanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('index/', views.index, name='index'),
    path('accounts/signup/', views.signup, name='signup'),
    path('organizations/new', views.organizations_new, name='organizations_new'), 
    path('organizations/create', views.organizations_create, name='organizations_create'),
    path('organizations/assoc_employee', views.assoc_org_employee, name='assoc_org_employee'),
    path('departments/index', views.departments_index, name='departments_index'), 
    path('departments/create', views.departments_create, name='departments_create'),
    path('departments/<int:department_id>/', views.departments_detail, name='departments_detail'),
    path('departments/<int:pk>/update/', views.DepartmentUpdate.as_view(), name='departments_update'),
    path('departments/<int:pk>/delete/', views.DepartmentDelete.as_view(), name='departments_delete'), 
    path('departments/<int:department_id>/tasks_create/', views.tasks_create, name='tasks_create'),
    path('tasks/<int:task_id>/', views.tasks_detail, name='tasks_detail'),
    path('departments/<int:department_id>/tasks/<int:pk>/delete', views.TaskDelete.as_view(), name='tasks_delete'),
    path('employees/<int:employee_id>/', views.employees_detail, name='employees_detail'), 
    path('employees/', views.employees_index, name='employees_index'), 
    path('employees/<int:employee_id>/assoc_dept_employee/', views.assoc_dept_employee, name='assoc_dept_employee'),
    path('tasks/<int:task_id>/update/', views.tasks_update, name='tasks_update'),
    path('departments/<int:department_id>/tasks/<int:pk>/delete/', views.TaskDelete.as_view(), name='tasks_delete'),
    path('tasks/<int:task_id>/assoc_task_employee/', views.assoc_task_employee, name='assoc_task_employee'), 
    path('tasks/<int:task_id>/remove_task_employee/', views.remove_task_employee, name='remove_task_employee')
]

main_app/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from django.urls import reverse


TASKURGENCY = (
    ('LOW', 'Low Priority'), 
    ('MID', 'Medium Priority'), 
    ('HIGH', 'High Priority'), 
    ('EMERG', 'EMERGENCY PRIORITY!')
)
TASKSTATUS = (
    ('IP', 'In Progress'), 
    ('AS', 'Assigned'), 
    ('UAS', 'Unassigned'), 
    ('COM', 'Complete'), 
)

class Organization(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

class Department(models.Model):
    name = models.CharField(max_length=30)
    org = models.ForeignKey(Organization, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('departments_detail', kwargs={'department_id': self.id})

class Task(models.Model):
    name = models.CharField(max_length=50)
    due = models.DateField('Due Date')
    description = models.TextField(max_length=300)
    status = models.CharField(
        max_length=3, 
        choices=TASKSTATUS, 
        default=TASKSTATUS[0][0]
        )
    urgency = models.CharField(
        max_length=5,
        choices=TASKURGENCY, 
        default=TASKURGENCY[0][0]
    )
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-due']

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dept = models.ManyToManyField(Department)
    org = models.ForeignKey(Organization, on_delete=models.CASCADE)
    task = models.ManyToManyField(Task)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

main_app/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from main_app.models import Organization, Department, Task, Employee

TASKURGENCY = (
    ('LOW', 'Low Priority'), 
    ('MID', 'Medium Priority'), 
    ('HIGH', 'High Priority'), 
    ('EMERG', 'EMERGENCY PRIORITY!')
)
TASKSTATUS = (
    ('IP', 'In Progress'), 
    ('AS', 'Assigned'), 
    ('UAS', 'Unassigned'), 
    ('COM', 'Complete'), 
)

class UserForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()

    class Meta:
        model = User
        fields = ('first_name','last_name', 'username', 'password1' ,'password2' )

class OrgForm(ModelForm):
    class Meta:
        model = Organization
        fields = ['name']

class DeptForm(ModelForm):
    class Meta:
        model = Department
        fields = ['name']

class TaskForm(forms.Form):
        name = forms.CharField(initial = 'Task')
        due = forms.DateField(widget = forms.SelectDateWidget)
        description = forms.CharField(widget = forms.Textarea)
        status = forms.MultipleChoiceField(choices = TASKSTATUS)
        urgency = forms.MultipleChoiceField(choices = TASKURGENCY)

main_app/views.py
from telnetlib import STATUS
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .forms import OrgForm, UserForm, DeptForm, TaskForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from datetime import *


from .models import Department, Organization, Task, Employee


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def index(request):
    pass

def signup(request):
    if request.user.id:
        return redirect('home')
    error_message = ''
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
    
            user = form.save()
            login(request, user)
            return redirect('organizations_new')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


### Organization 

@login_required
def organizations_new(request):
    if hasattr(request.user, 'employee') and hasattr(request.user.employee, 'org_id'):
        return redirect('home')
    orgs = Organization.objects.all()
    org_form = OrgForm()
    context = { 'orgs': orgs, 'org_form': org_form }
    return render(request, 'organizations/organization_form.html', context)

@login_required
def organizations_create(request):
    if hasattr(request.user, 'employee') and hasattr(request.user.employee, 'org_id'):
        return redirect('home')
    form = OrgForm(request.POST)
    if form.is_valid():
        form.save()
    org = Organization.objects.get(name=request.POST['name'])
    Employee.objects.create(user_id=request.user.id, org_id=org.id)
    return redirect('departments_index')

@login_required
def assoc_org_employee(request):
    Employee.objects.create(user_id=request.user.id, org_id=request.POST['org_id'])
    return redirect('home')


### Departments

@login_required
def departments_index(request):
    depts = Department.objects.filter(org_id = request.user.employee.org_id)
    dept_form = DeptForm()
    context = { 'depts': depts, 'dept_form': dept_form}
    return render(request, 'departments/department_form.html', context)


def departments_create(request):
    form = DeptForm(request.POST)
    if form.is_valid():
        department = form.save(commit=False)
        department.org_id = request.user.employee.org.id
        form.save()
    return redirect('departments_index')

@login_required
def departments_detail(request, department_id):
    department = get_object_or_404(Department, id=department_id)
    if department.org_id != request.user.employee.org_id:
        return redirect('departments_index')
    task_form = TaskForm()
    tasks = department.task_set.all()
    employees = department.employee_set.all()
    return render(request, 'departments/department_detail.html', {'department':department, 'tasks': tasks, 'task_form': task_form, 'employees': employees })

class DepartmentUpdate(LoginRequiredMixin, UpdateView):
    model = Department
    fields = ['name']
    template_name = 'departments/department_update.html'

class DepartmentDelete(LoginRequiredMixin, DeleteView):
	model = Department
	success_url = "/"

### Tasks

@login_required
def tasks_create(request, department_id):
    dat_form = TaskForm(request.POST)

    if dat_form.is_valid():

        clean_form = dat_form.cleaned_data
        print(clean_form)

        all_together_now = Task(
            name = clean_form['name'],
            due = clean_form['due'],
            description = clean_form['name'],
            status = clean_form['status'][0],
            urgency = clean_form['urgency'][0],
            department_id = department_id 
        )
        all_together_now.save()


    return redirect('departments_detail', department_id = department_id)


@login_required
def tasks_detail(request, task_id):
    task = Task.objects.get(id = task_id)
    employee = Employee.objects.get(id = request.user.employee.id)
    avlemp = Employee.objects.filter(org_id = employee.org.id).exclude(id__in=task.employee_set.all())
    asgnemp = Employee.objects.filter(id__in=task.employee_set.all())
    print(asgnemp)
    return render(request, 'tasks/task_detail.html', {'employee':employee, 'task':task, 'avlemp':avlemp, 'asgnemp':asgnemp})

def tasks_update(request, task_id):

    task = get_object_or_404(Task, id = task_id)

    form = TaskForm(request.POST or None)
    

    if form.is_valid():
        
        clean_form = form.cleaned_data
        print(task)
        clean_form['due'] = clean_form['due'].strftime('%Y-%m-%d')
        
        

        task.name = clean_form['name']
        task.due = clean_form['due']
        task.description = clean_form['description']
        task.status = clean_form['status'][0]
        task.urgency = clean_form['urgency'][0]
        
        print(task.due)
        task.save(update_fields=['name', 'due', 'description', 'status', 'urgency'])
        
        return redirect('tasks_detail', task_id)


    return render(request, "tasks/task_form.html", {'task_form': form, 'task' : task})

    
class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    def get_success_url(self, **kwargs):
        return reverse('departments_detail', args=[self.kwargs['department_id']])

@login_required
def assoc_task_employee(request, task_id):
    task = Task.objects.get(id = task_id)
    employee = Employee.objects.get(id = request.POST['employee'])
    employee.task.add(task_id)
    return redirect('tasks_detail', task_id)

def remove_task_employee(request, task_id):
    task = Task.objects.get(id = task_id)
    employee = Employee.objects.get(id = request.POST['employee'])
    employee.task.remove(task_id)
    return redirect('tasks_detail', task_id)


### Employees

@login_required
def employees_detail(request, employee_id):
    employee = Employee.objects.get(id=employee_id)
    tasks = employee.task.all()
    departments = employee.dept.all()
    excludedept = employee.dept.all().values_list('id')
    avldepts = Department.objects.filter(org_id = employee.org_id).exclude(id__in=excludedept)
    return render(
        request, 
        'employees/employee_detail.html', 
        {'tasks': tasks, 'employee': employee, 'departments': departments, 'avldepts': avldepts})

@login_required
def employees_index(request):
    employees = Employee.objects.filter(org_id = request.user.employee.org_id)
    return render(request, 'employees/employee_index.html',{'employees': employees})

@login_required
def assoc_dept_employee(request, employee_id): 
    employee = Employee.objects.get(id = employee_id)
    employee.dept.add(request.POST['dept'])
    return redirect('employees_detail', employee_id)

main_app/templates/departments/department_detail.html
{% extends 'base.html' %}
{% block title %}
    {{department.name}} Details
{% endblock %}


{% block content %}


<div class="container mt-4">
    <div class="row">
        <div class="col-6">
            <h1>Department: {{department.name}}</h1>
            <a href="{% url 'departments_update' department.id %}"><button class="btn btn-sm btn-outline-dark">Update Department</button></a>
            <a href="{% url 'departments_delete' department.id %}"><btn class="btn btn-sm btn-danger">Delete Department</btn></a>
        </div>

        <div class="col-6">
            <h3 class="text-center">Employees</h3>
            <div class="text-center">
            {% for employee in employees|dictsort:"user.first_name" %}
                <a href="{% url 'employees_detail' employee.id %}" class="btn btn-sm btn-outline-dark">{{ employee.user.first_name|capfirst }} {{ employee.user.last_name|capfirst }}</a>
            {% endfor %}
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-6">
            <div>
                <h3 class="text-center">Create a Task</h3>
                <form method="POST" action="{% url 'tasks_create' department.id %}">
                    {% csrf_token %}
                    <table class="table table-sm">
                        {{ task_form.as_table }}
                    </table>
                <input type="submit" value="Create Task" class="btn btn-sm btn-primary">
                </form>

            </table>
            </div>
        </div>
        <div class="col-6">
            <div>
                <!-- Tasks Start -->
                <h3 class="text-center">Department Tasks</h3>
                <table class="table table-sm">
                    <thead>
                        <th>Task</th>
                        <th>Due Date</th>
                        <th>Assigned Employees</th>
                        <th>Urgency</th>
                        <th>Description</th>
                        <th>Status</th>
                        <th>Details</th>
                        <th>Delete</th>
                    </thead>
                    <tbody>
                {% for task in tasks %}
                    {% if task.status == 'COM' %}
                        <tr class="table-active">
                    {% elif task.urgency == 'HIGH' %}
                        <tr class="table-warning">
                    {% elif task.urgency == 'EMERG' %}
                        <tr class="table-danger">
                    {% else %}
                        <tr>
                    {% endif %}
                            <td> {{ task.name }} </td>
                            <td> {{ task.due }} </td>
                            <td>
                                {% for employee in task.employee_set.all %}
                                {{ employee.user.first_name|capfirst }} {{ employee.user.last_name|capfirst }} 
                                {% endfor%} 
                            </td>        
                            <td> {{ task.get_urgency_display }} </td>
                            <td> {{ task.description }} </td>
                            <td> {{ task.get_status_display }} </td>
                            <td><a href="{% url 'tasks_detail' task.id %}" >Task Info</a></td>
                            <td><a href="{% url 'tasks_delete' department.id task.id %}" class="btn btn-sm btn-danger">X</a></td>
                        </tr>

                {% endfor %}
                    </tbody>
                </table>
            </div>


        </div>
    </div>

</div>
<!-- new stuff -->


<!-- Tasks End -->
{% endblock %}

main_app/templates/departments/department_form.html
{% extends 'base.html' %}
{% block title %}
    {{department.name}} Departments
{% endblock %}

{% block content %}
<br>
<br>
<div class="container">
  <div class="row">
      <div class="col">
          <div>
              
          </div>
      </div>

      <div class="col-8">
          <div class="h5 container-fluid text-center">
            <h2 class="text-muted">Departments in {{ request.user.employee.org }}</h2>
            {% csrf_token %}
            {% for dept in depts %}
            
                <a href="{% url 'departments_detail' dept.id %}">
                    <div class="card">
                        <div class="card-body">
                          Department: {{ dept.name }}
                        </div>
                    </div>
                </a>
            
            {% endfor %}
            <br>
            <br>
            <h2 class="text-muted">Create a Dept</h2>

            <form method="POST" action="{% url 'departments_create' %}">

              {{ dept_form.as_p }}
              {% csrf_token %}
              <input type="submit" value="Create Department" class="btn btn-sm btn-primary">
            </form>
          </div>
      </div>
      <div class="col">
          <div>
              
          </div>
      </div>
  </div>

</div>




{% endblock %}

main_app/templates/departments/department_update.html
{% extends 'base.html' %}
{% block title %}
    {{department.name}} Update
{% endblock %}

{% block content %}
<div class="container m-auto text-center mt-4">
    <h4>Update Department: {{department.name}}</h4>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-sm btn-outline-dark" value="Update">
    </form>
</div>

{% endblock %}